askisi5 : main.o STACKImplementation.o path.o
	gcc main.o STACKImplementation.o path.o -o askisi5
main.o : main.c STACK.h Item.h Header.h
	gcc -c main.c
STACKImplementation.o : STACKImplementation.c STACK.h Item.h 
	gcc -c STACKImplementation.c
path.o : path.c STACK.h Item.h Header.h
	gcc -c path.c
clean : 
	rm askisi5 main.o STACKImplementation.o path.o